# basic info
title: 2nd multipage test
author: red bullion
email: r3d@redbullion.com
description: attempt to replicate in van same as sf-iteration
twitter_username: tbd+rrtUK
github_username:  rrtUK

# Build settings
markdown: kramdown
theme: minima
